# src/AppBundle/Resources/config/validation.yml
AppBundle\Entity\Project:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: id
    properties:
        name:
            - NotBlank: ~
            - Type: string


AppBundle\Entity\Note:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: id
    properties:
        name:
            - NotBlank: ~
            - Type: string

AppBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
    properties:
        firstname:
            - NotBlank: ~
            - Type: string
        lastname:
            - NotBlank: ~
            - Type: string
        email:
            - Email:
                message: The email "{{ value }}" is not a valid email.
                checkMX: true
