# src/AppBundle/Resources/config/serializer/Entity.Note.yml
AppBundle\Entity\Note:
    exclusion_policy: none
    properties:
        id:
            groups: ['project', 'note']
        name:
            groups: ['project', 'note']
        content:
            groups: ['project', 'note']
        createdAt:
            groups: ['project', 'note']
        updatedAt:
            groups: ['project', 'note']
        project:
            groups: ['note']